LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: ruby19

SpaceBeforeFirstArg:
  Enabled: false

TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
